/// A table of the data files.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum DataTable {
    Mode,
    ModeCombat,
    ModeNavigation,
    SlotKind,
    Choice,
    Leech,
    Relation,
    Players,
    Action,
    Effect,
    Delivery,
    Projectile,
    Area,
    AreaInside,
    Track,
    Modifier,
    Aura,
    Combat,
    Production,
    Vision,
    Collision,
    Ai,
    Tag,
    Item,
    Inventory,
    Shop,
}
impl DataTable {
    pub const ALL: [DataTable; 26] = [
        DataTable::Mode,
        DataTable::ModeCombat,
        DataTable::ModeNavigation,
        DataTable::SlotKind,
        DataTable::Choice,
        DataTable::Leech,
        DataTable::Relation,
        DataTable::Players,
        DataTable::Action,
        DataTable::Effect,
        DataTable::Delivery,
        DataTable::Projectile,
        DataTable::Area,
        DataTable::AreaInside,
        DataTable::Track,
        DataTable::Modifier,
        DataTable::Aura,
        DataTable::Combat,
        DataTable::Production,
        DataTable::Vision,
        DataTable::Collision,
        DataTable::Ai,
        DataTable::Tag,
        DataTable::Item,
        DataTable::Inventory,
        DataTable::Shop,
    ];

    /// The table as the reference titles it.
    pub const fn title(self) -> &'static str {
        match self {
            DataTable::Mode => "`data/mode.toml`",
            DataTable::ModeCombat => "The mode's `[combat]`",
            DataTable::ModeNavigation => "The mode's `[navigation]`",
            DataTable::SlotKind => "A slot kind, `[[slots]]`",
            DataTable::Choice => "A choice, `[choices.<name>]`",
            DataTable::Leech => "The mode's `[combat] leech`",
            DataTable::Relation => "A pair of teams, `[[relations]]`",
            DataTable::Players => "The mode's `[players]`",
            DataTable::Action => "An action, `[actions.<id>]`",
            DataTable::Effect => "An effect of an action's `on_resolve`, `on_hit` or `on_end`",
            DataTable::Delivery => "An action's `delivery`",
            DataTable::Projectile => "A unit type's `projectile`",
            DataTable::Area => "A unit type's `area`",
            DataTable::AreaInside => "An area's `inside`",
            DataTable::Track => "A track, `[tracks.<name>]`",
            DataTable::Modifier => "A modifier, `[modifiers.<id>]`",
            DataTable::Aura => "A modifier's `aura`",
            DataTable::Combat => "A unit type's `combat`",
            DataTable::Production => "A unit type's `production`",
            DataTable::Vision => "A unit type's `vision`",
            DataTable::Collision => "A unit type's `collision`",
            DataTable::Ai => "A unit type's `orders`",
            DataTable::Tag => "A tag's effects, `[tags.<name>]`",
            DataTable::Item => "An item type, `[items.<id>]`",
            DataTable::Inventory => "A unit type's `inventory`",
            DataTable::Shop => "The mode's `[shop]`",
        }
    }
}
