[package]
name = "campfire-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
campfire-common.workspace = true
campfire-log.workspace = true
campfire-net.workspace = true
campfire-package.workspace = true
campfire-protocol.workspace = true
campfire-runner.workspace = true
campfire-sim.workspace = true
campfire-store.workspace = true

bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_state.workspace = true
bevy_time.workspace = true
lightyear.workspace = true
thiserror.workspace = true
tracing.workspace = true
wtransport.workspace = true

[lints]
workspace = true
