[package]
name = "campfire-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
campfire-log = { workspace = true, features = ["start"] }
campfire-capabilities.workspace = true
campfire-common.workspace = true
campfire-math.workspace = true
campfire-net.workspace = true
campfire-package.workspace = true
campfire-protocol.workspace = true
campfire-runner.workspace = true
campfire-sim.workspace = true
campfire-store.workspace = true

bevy.workspace = true
clap.workspace = true
lightyear.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
campfire-capabilities = { workspace = true, features = ["internals"] }
campfire-import = { workspace = true, features = ["internals"] }
campfire-store = { workspace = true, features = ["internals"] }

[lints]
workspace = true
