[package]
name = "campfire-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
campfire-log.workspace = true
campfire-capabilities.workspace = true
campfire-common.workspace = true
campfire-math.workspace = true
campfire-net.workspace = true
campfire-package.workspace = true
campfire-protocol.workspace = true
campfire-runner.workspace = true
campfire-sim.workspace = true

bevy.workspace = true
clap.workspace = true
lightyear.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
