[package]
name = "campfire-verifier"
version.workspace = true
edition.workspace = true
license.workspace = true
autotests = false

[dependencies]
campfire-common.workspace = true
campfire-log = { workspace = true, features = ["start"] }
campfire-package.workspace = true
campfire-protocol.workspace = true
campfire-runner.workspace = true
campfire-sim.workspace = true
campfire-store.workspace = true

clap.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
campfire-log = { workspace = true, features = ["internals"] }
campfire-runner = { workspace = true, features = ["internals"] }
campfire-capabilities.workspace = true
campfire-math.workspace = true
campfire-package = { workspace = true, features = ["internals"] }
campfire-store = { workspace = true, features = ["internals"] }


[lints]
workspace = true

[[test]]
name = "tests"
path = "tests/mod.rs"
