[package]
name = "campfire-package"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
campfire-capabilities.workspace = true
campfire-content.workspace = true
campfire-math.workspace = true
campfire-script.workspace = true
campfire-sim.workspace = true

postcard.workspace = true
serde.workspace = true
sha2.workspace = true
toml.workspace = true

[lints]
workspace = true
