[package]
name = "campfire-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
internals = []

[dependencies]
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
