[package]
name = "campfire-sim"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
internals = []
bench = ["internals", "dep:criterion"]

[dependencies]
campfire-math.workspace = true

bevy_ecs.workspace = true
blake3.workspace = true
criterion = { workspace = true, optional = true }
postcard.workspace = true
serde.workspace = true

[[bench]]
name = "state_hash"
harness = false
required-features = ["bench"]

[lints]
workspace = true
