[package]
name = "campfire-capabilities"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
campfire-content.workspace = true
campfire-math.workspace = true
campfire-script.workspace = true
campfire-sim.workspace = true

bevy_ecs.workspace = true
postcard.workspace = true
serde.workspace = true

[lints]
workspace = true
