[package]
name = "campfire-capabilities"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
bench = ["dep:criterion"]

[dependencies]
campfire-content.workspace = true
campfire-math.workspace = true
campfire-script.workspace = true
campfire-sim.workspace = true

bevy_ecs.workspace = true
criterion = { workspace = true, optional = true }
postcard.workspace = true
serde.workspace = true

[[bench]]
name = "collision"
harness = false
required-features = ["bench"]

[lints]
workspace = true
