[package]
name = "campfire-verifier"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
campfire-content.workspace = true
campfire-identity.workspace = true
campfire-protocol.workspace = true
campfire-runner.workspace = true

[dev-dependencies]
campfire-capabilities.workspace = true
campfire-math.workspace = true
campfire-sim.workspace = true

[lints]
workspace = true
