[package]
name = "campfire-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
autotests = false

[features]
internals = ["dep:campfire-math"]
bench = ["internals", "dep:criterion"]

[dependencies]
campfire-capabilities.workspace = true
campfire-content.workspace = true
campfire-math = { workspace = true, optional = true }
campfire-package.workspace = true
campfire-protocol.workspace = true
campfire-script.workspace = true
campfire-sim.workspace = true

bevy_ecs.workspace = true
criterion = { workspace = true, optional = true }
tracing.workspace = true

[dev-dependencies]
campfire-math.workspace = true

[lints]
workspace = true

[[test]]
name = "tests"
path = "tests/mod.rs"
required-features = ["internals"]

[[bench]]
name = "tick_3v3"
harness = false
required-features = ["bench"]
