[package]
name = "campfire-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
autotests = false

[dependencies]
campfire-capabilities.workspace = true
campfire-content.workspace = true
campfire-package.workspace = true
campfire-protocol.workspace = true
campfire-script.workspace = true
campfire-sim.workspace = true

bevy_ecs.workspace = true
tracing.workspace = true

[dev-dependencies]
campfire-math.workspace = true

[lints]
workspace = true

[[test]]
name = "tests"
path = "tests/mod.rs"
